name: API Build and Test
on:
  pull_request: 
    branches:
      - main
    paths:
      - '.github/workflows/api-build-and-test.yml'
      - 'src/Kaizen.API/**'
      - 'test/Kaizen.API.FunctionalTests/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}@${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and Test API
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        
      - name: Setup .NET 9.0.x
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: 9.0.x
          
      - name: Ensure Docker is available for TestContainers
        run: docker --version
        
      - name: Restore Dependencies
        run: dotnet restore 
        
      - name: Build
        run: dotnet build -c Release --no-restore
        
      - name: Run Tests
        run: dotnet test -c Release --no-build --verbosity normal
