name: API Build and Test
on:
  pull_request: 
    branches:
      - main
    paths:
      - 'src/Kaizen.API/**'
      - 'test/Kaizen.API.FunctionalTests/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        
      - name: Setup .NET 9.0.x
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: 9.0.x
        
      - name: Restore Dependencies
        run: dotnet restore src/Kaizen.API/Kaizen.API.csproj
        
      - name: Build
        run: dotnet build src/Kaizen.API/Kaizen.API.csproj --configuration Release --no-restore
        
      - name: Run Functional Tests
        run: dotnet test test/Kaizen.API.FunctionalTests/Kaizen.API.FunctionalTests.csproj --configuration Release --no-build --verbosity normal
